modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
showAsResourcePack=false

[[mods]]
modId="guardmod"
version="1.0.0"
displayName="Защита Сервера"
authors="Kombo3D"
credits="Спасибо всем, кто помогает с тестированием и развитием мода."
description='''
Мод на систему защиты сервера для Minecraft Forge 1.20.1.

В моде реализованы:
- проверка модов;
- проверка шейдеров;
- проверка ресурспаков;

Мод рассчитан на сервера, где важна честная игра
'''

[[dependencies.guardmod]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.guardmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
