modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="settlements"
version="1.0.0"
displayName="Settlements"
authors="Daniil Shuraev"
description='''
Мод поселений и магазинов.
'''

[[dependencies.settlements]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.settlements]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"